"use client"

import { Brain, CheckCircle2, AlertTriangle, Target } from "lucide-react"

interface PitchSummaryProps {
  visible: boolean
}

const summaryPoints = [
  {
    icon: CheckCircle2,
    label: "Strong Value Proposition",
    detail: "Clear problem-solution fit targeting a $4.2B addressable market with unique AI-driven approach.",
    type: "positive" as const,
  },
  {
    icon: Target,
    label: "Market Opportunity",
    detail: "Growing TAM with 23% YoY growth. Early-mover advantage in the AI-assisted workflow space.",
    type: "positive" as const,
  },
  {
    icon: AlertTriangle,
    label: "Revenue Model Clarity",
    detail: "SaaS pricing strategy is solid but consider enterprise tiers for B2B segment expansion.",
    type: "warning" as const,
  },
  {
    icon: CheckCircle2,
    label: "Team Composition",
    detail: "Technical co-founders with domain expertise. Consider adding a growth/marketing lead.",
    type: "positive" as const,
  },
]

export function PitchSummaryPanel({ visible }: PitchSummaryProps) {
  if (!visible) return null

  return (
    <div className="glass rounded-2xl p-6 animate-fade-in-up">
      <div className="mb-6 flex items-center gap-3">
        <div className="flex h-9 w-9 items-center justify-center rounded-lg gradient-primary-subtle">
          <Brain className="h-4.5 w-4.5 text-violet-400" />
        </div>
        <div>
          <h2 className="font-display text-lg font-semibold text-foreground">AI Pitch Summary</h2>
          <p className="text-xs text-muted-foreground">Generated by our multi-model analysis pipeline</p>
        </div>
      </div>

      {/* Executive Summary */}
      <div className="mb-6 rounded-xl bg-gradient-to-br from-violet-950/30 to-purple-950/20 border border-violet-500/10 p-4">
        <p className="text-sm leading-relaxed text-foreground/80">
          Your startup presents a compelling AI-powered productivity platform targeting mid-market B2B
          companies. The pitch demonstrates strong technical differentiation with a clear path to monetization.
          Key areas of investor interest include the proprietary model architecture and early customer traction
          with 3 pilot enterprise clients.
        </p>
      </div>

      {/* Key Points */}
      <div className="flex flex-col gap-3">
        {summaryPoints.map((point, i) => (
          <div
            key={point.label}
            className="flex items-start gap-3 rounded-xl border border-border/50 p-3 animate-fade-in-up"
            style={{ animationDelay: `${0.1 * (i + 1)}s` }}
          >
            <point.icon
              className={`mt-0.5 h-4 w-4 shrink-0 ${
                point.type === "positive" ? "text-violet-400" : "text-amber-400"
              }`}
            />
            <div>
              <p className="text-sm font-medium text-foreground">{point.label}</p>
              <p className="text-xs leading-relaxed text-muted-foreground">{point.detail}</p>
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}
